 -- ComboAnidado
 
 CREATE TABLE "COMBOANIDADO"."DEPARTAMENTO" 
   (	"CODDEPART" NUMBER, 
	"NOMDEPART" VARCHAR2(60 BYTE), 
	 CONSTRAINT "DEPARTAMENTO_PK" PRIMARY KEY ("CODDEPART")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
----------
  
  CREATE TABLE "COMBOANIDADO"."PROVINCIA" 
   (	"CODPROV" NUMBER, 
	"NOMPROV" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"CODDEPART" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PROVINCIA_PK" PRIMARY KEY ("CODPROV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CODDEPART_FK" FOREIGN KEY ("CODDEPART")
	  REFERENCES "COMBOANIDADO"."DEPARTAMENTO" ("CODDEPART") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
----------

CREATE TABLE "COMBOANIDADO"."DISTRITO" 
   (	"CODDIST" NUMBER, 
	"NOMDIST" VARCHAR2(60 BYTE), 
	"CODPROV" NUMBER, 
	 CONSTRAINT "DISTRITO_PK" PRIMARY KEY ("CODDIST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CODPROV_FK" FOREIGN KEY ("CODPROV")
	  REFERENCES "COMBOANIDADO"."PROVINCIA" ("CODPROV") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
--- DATOS

Insert into COMBOANIDADO.DEPARTAMENTO (CODDEPART,NOMDEPART) values ('123456','LIMA');
Insert into COMBOANIDADO.DEPARTAMENTO (CODDEPART,NOMDEPART) values ('123457','UCAYALI');
Insert into COMBOANIDADO.DEPARTAMENTO (CODDEPART,NOMDEPART) values ('123458','CAJAMARCA');

Insert into COMBOANIDADO.PROVINCIA (CODPROV,NOMPROV,CODDEPART) values ('5','ATALAYA','123457');
Insert into COMBOANIDADO.PROVINCIA (CODPROV,NOMPROV,CODDEPART) values ('6','PADRE ABAD','123457');
Insert into COMBOANIDADO.PROVINCIA (CODPROV,NOMPROV,CODDEPART) values ('7','PURUS','123457');
Insert into COMBOANIDADO.PROVINCIA (CODPROV,NOMPROV,CODDEPART) values ('1','CAÑETE','123456');
Insert into COMBOANIDADO.PROVINCIA (CODPROV,NOMPROV,CODDEPART) values ('2','YAUYOS','123456');
Insert into COMBOANIDADO.PROVINCIA (CODPROV,NOMPROV,CODDEPART) values ('3','HUARAL','123456');
Insert into COMBOANIDADO.PROVINCIA (CODPROV,NOMPROV,CODDEPART) values ('4','CANTA','123456');

Insert into COMBOANIDADO.DISTRITO (CODDIST,NOMDIST,CODPROV) values ('1','ZUÑIGA','1');
Insert into COMBOANIDADO.DISTRITO (CODDIST,NOMDIST,CODPROV) values ('2','PACARAN','1');
Insert into COMBOANIDADO.DISTRITO (CODDIST,NOMDIST,CODPROV) values ('3','LUNAHUANA','1');
Insert into COMBOANIDADO.DISTRITO (CODDIST,NOMDIST,CODPROV) values ('4','IMPERIAL','1');
Insert into COMBOANIDADO.DISTRITO (CODDIST,NOMDIST,CODPROV) values ('5','SAN VICENTE','1');
Insert into COMBOANIDADO.DISTRITO (CODDIST,NOMDIST,CODPROV) values ('6','SAN LUIS','1');
Insert into COMBOANIDADO.DISTRITO (CODDIST,NOMDIST,CODPROV) values ('7','CERRO AZUL','1');
Insert into COMBOANIDADO.DISTRITO (CODDIST,NOMDIST,CODPROV) values ('8','QUILMANA','1');
Insert into COMBOANIDADO.DISTRITO (CODDIST,NOMDIST,CODPROV) values ('9','SAN ANTONIO','1');
  
